#cloud-config

coreos:
    etcd:
        discovery: https://discovery.etcd.io/d634d28c72377c7c5e622766ec8b8521
        addr: $private_ipv4:4001
        peer-addr: $private_ipv4:7001
    units:
        - name: etcd.service
          command: start
        - name: fleet.service
          command: start
