api:
    restart: always
    build: ./dss.api
    ports:
        - "8000:8000"
    links:
        - postgres:postgres
    env_file: .env
    #command: /usr/local/bin/gunicorn dss.wsgi:application -w 2 -b :8000
    command: python manage.py runserver_plus 0.0.0.0:8000

postgres:
    restart: always
    image: postgres:latest
    volumes_from:
        - data
    ports:
        - "5432:5432"
data:
  restart: no
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: /bin/true
