rabbitmq:
    image: tutum/rabbitmq
    environment:
        - RABBITMQ_PASS=wZ59kFTJZN8YQ
    ports: 
        - "4369:4369"
        - "5672:5672"
        - "15672:15672"

postgres:
    restart: always
    image: postgres:latest
    volumes_from:
        - data
    ports:
        - "5432:5432"

redis:
    image: redis

data:
  restart: no
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: /bin/true

celery:
    build: ./dss.api
    volumes_from:
        - api
    links:
        - "postgres:postgres"
        - "redis:redis"
        - "rabbitmq:rabbitmq"
    command: ./run_celery.sh
    #command: python manage.py celeryd

api:
    build: ./dss.api
    volumes:
        - /files
    ports:
        - "8001:8001"
    links:
        - "postgres:postgres"
        - "redis:redis"
        - "rabbitmq:rabbitmq"
    command: ./run_web.sh

web:
    restart: always
    build: ./dss.web
    links:
        - "redis:redis"
    ports:
        - "8080:8080"

nginx:
    restart: always
    build: ./nginx/
    ports:
        - "80:80"
        - "443:443"
    links:
        - "api:api"
        - "web:web"
        - "icecast:icecast"
    volumes_from:
        - api
icecast:
    image: moul/icecast:latest
    volumes:
        - ./logs:/var/log/icecast2
        - /etc/localtime:/etc/localtime:ro 
    environment:
        - ICECAST_SOURCE_PASSWORD=RDzNlgqmj67vk
        - ICECAST_ADMIN_PASSWORD=CrVuP5evoJZ0.
        - ICECAST_RELAY_PASSWORD=9PmUbI1mLne9o
    ports:
        - 8000:8000
radio:
    build: dss.radio/
    ports:
        - "8888:8888"
