data:
  restart: "no"
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql
  command: /bin/true

postgres:
    restart: "always"
    image: postgres:9.4
    volumes_from:
        - data
    ports:
        - "5432:5432"

rabbitmq:
    image: tutum/rabbitmq
    environment:
        - RABBITMQ_PASS=wZ59kFTJZN8YQ
    ports:
        - "4369:4369"
        - "5672:5672"
        - "15672:15672"

redis:
    image: redis

api:
   image: fergalmoran/dss.api
   volumes:
     - /files
   ports:
     - "8001:8001"
   env_file:
       - ./api_env
   links:
       - postgres
       - redis
#       - icecast
       - rabbitmq
   command: ./run_web.sh

icecast:
    build: ./icecast/
    volumes:
        - ./logs:/var/log/icecast2
        - /etc/localtime:/etc/localtime:ro
    environment:
        - ICECAST_SOURCE_PASSWORD=RDzNlgqmj67vk
        - ICECAST_ADMIN_PASSWORD=CrVuP5evoJZ0
        - ICECAST_RELAY_PASSWORD=9PmUbI1mLne9o
    ports:
        - 8000:8000

api:
    image: fergalmoran/dss.api
    volumes:
        - /files
    ports:
        - "8001:8001"
    env_file:
        - ./api_env
    links:
        - "postgres:postgres"
        - "redis:redis"
        - "icecast:icecast"
        - "rabbitmq:rabbitmq"
    command: ./run_web.sh

celery:
    image: fergalmoran/dss.api
    env_file:
        - ./api_env
    volumes_from:
        - api
    links:
        - "postgres:postgres"
        - "redis:redis"
        - "rabbitmq:rabbitmq"
    command: ./run_celery.sh

web:
    image: fergalmoran/dss.web
    env_file:
        - ./web_env
    restart: "always"
    links:
        - "redis:redis"
    ports:
        - "8080:8080"

#icecast:
#    build: ./icecast/
#    volumes:
#        - ./logs:/var/log/icecast2
#        - /etc/localtime:/etc/localtime:ro
#    environment:
#        - ICECAST_SOURCE_PASSWORD=RDzNlgqmj67vk
#        - ICECAST_ADMIN_PASSWORD=CrVuP5evoJZ0
#        - ICECAST_RELAY_PASSWORD=9PmUbI1mLne9o
#    ports:
#        - 8000:8000

#radio:
#    image: fergalmoran/dss.radio
#    env_file:
#        - ./radio_env
#    ports:
#        - "8888:8888"
#    links:
#        - "icecast:icecast"
#        - "api:api"

nginx:
    restart: "always"
    build: ./nginx/
    ports:
        - "80:80"
        - "443:443"
    links:
        - "api:api"
        - "web:web"
 #       - "icecast:icecast"
 #       - "radio:radio"
    volumes_from:
        - api

